version: "3.8"

networks:
  app_network:
    driver: bridge

volumes:
  pb_data:
  pb_public:
  pb_hooks:
  pb_migrations:
  node_modules:

services:
  pocketbase:
    container_name: pocketbase
    build:
      context: .
      dockerfile: pocketbase.Dockerfile
    restart: unless-stopped
    ports:
      - "8092:8092"
    volumes:
      - pb_data:/pb/pb_data
      - pb_public:/pb/pb_public
      - pb_hooks:/pb/pb_hooks
      - pb_migrations:/pb/pb_migrations
    networks:
      - app_network
    healthcheck:
      test:
        ["CMD", "wget", "-q", "--spider", "http://localhost:8092/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - DISABLE_GZIP=true

  app:
    container_name: app
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - pocketbase
    env_file:
      - .env
    environment:
      - PUBLIC_POCKETBASE_URL=${PUBLIC_POCKETBASE_URL}
      - PUBLIC_APPLICATION_NAME=${PUBLIC_APPLICATION_NAME}
      - PUBLIC_APPLICATION_URL=${PUBLIC_APPLICATION_URL}
      - ENCRYPTION=${ENCRYPTION}
      - POCKETBASE_ADMIN_EMAIL=${POCKETBASE_ADMIN_EMAIL}
      - POCKETBASE_ADMIN_PASSWORD=${POCKETBASE_ADMIN_PASSWORD}
      - METADATA_SCRAPER_URL=${METADATA_SCRAPER_URL}
      - HASH_ALGORITHM=${HASH_ALGORITHM}
      - HASH_KEY=${HASH_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_PRO_PRICE_ID=${STRIPE_PRO_PRICE_ID}
      - STRIPE_ENTERPRISE_PRICE_ID=${STRIPE_ENTERPRISE_PRICE_ID}
      - PUBLIC_SITE_URL=${PUBLIC_SITE_URL}
      - STRIPE_PRODUCT_ID=${STRIPE_PRODUCT_ID}

    networks:
      - app_network
    volumes:
      - .:/app
      - node_modules:/app/node_modules
