# Use a lightweight official Node image with Bun
FROM oven/bun:latest

# Set the working directory in the container
WORKDIR /app

# Copy the package and lock files
COPY package.json bun.lockb /app/

# Install dependencies
RUN bun install

# Copy the rest of the application code
COPY . .

# Build the SvelteKit app
RUN bun run build

# Expose the port SvelteKit runs on (default is 3000)
EXPOSE 5173

# Run the app
CMD ["bun", "run", "start:prod"]
