FROM alpine:latest

WORKDIR /pb

# Download and setup PocketBase in a single layer
RUN wget https://github.com/pocketbase/pocketbase/releases/download/v0.22.22/pocketbase_0.22.22_linux_amd64.zip \
    && unzip pocketbase_0.22.22_linux_amd64.zip \
    && rm pocketbase_0.22.22_linux_amd64.zip \
    && chmod +x /pb/pocketbase

# Create directory for the database
RUN mkdir /pb/pb_data

EXPOSE 8090

CMD ["/pb/pocketbase", "serve", "--http=0.0.0.0:8090"]
